/** 与 `src/lib/components/ui/<slug>` 一一对应；顺序稳定便于对照与锚点跳转。 */
export type ShowcaseEntry = {
	slug: string;
	title: string;
};

export const SHOWCASE_ENTRIES: ShowcaseEntry[] = [
	{ slug: "accordion", title: "Accordion" },
	{ slug: "alert", title: "Alert" },
	{ slug: "alert-dialog", title: "Alert Dialog" },
	{ slug: "aspect-ratio", title: "Aspect Ratio" },
	{ slug: "avatar", title: "Avatar" },
	{ slug: "badge", title: "Badge" },
	{ slug: "breadcrumb", title: "Breadcrumb" },
	{ slug: "button", title: "Button" },
	{ slug: "button-group", title: "Button Group" },
	{ slug: "calendar", title: "Calendar" },
	{ slug: "card", title: "Card" },
	{ slug: "carousel", title: "Carousel" },
	{ slug: "chart", title: "Chart" },
	{ slug: "checkbox", title: "Checkbox" },
	{ slug: "collapsible", title: "Collapsible" },
	{ slug: "command", title: "Command" },
	{ slug: "context-menu", title: "Context Menu" },
	{ slug: "data-table", title: "Data Table" },
	{ slug: "dialog", title: "Dialog" },
	{ slug: "drawer", title: "Drawer" },
	{ slug: "dropdown-menu", title: "Dropdown Menu" },
	{ slug: "empty", title: "Empty" },
	{ slug: "field", title: "Field" },
	{ slug: "form", title: "Form" },
	{ slug: "hover-card", title: "Hover Card" },
	{ slug: "input", title: "Input" },
	{ slug: "input-group", title: "Input Group" },
	{ slug: "input-otp", title: "Input OTP" },
	{ slug: "item", title: "Item" },
	{ slug: "kbd", title: "Kbd" },
	{ slug: "label", title: "Label" },
	{ slug: "menubar", title: "Menubar" },
	{ slug: "native-select", title: "Native Select" },
	{ slug: "navigation-menu", title: "Navigation Menu" },
	{ slug: "pagination", title: "Pagination" },
	{ slug: "popover", title: "Popover" },
	{ slug: "progress", title: "Progress" },
	{ slug: "radio-group", title: "Radio Group" },
	{ slug: "range-calendar", title: "Range Calendar" },
	{ slug: "resizable", title: "Resizable" },
	{ slug: "scroll-area", title: "Scroll Area" },
	{ slug: "select", title: "Select" },
	{ slug: "separator", title: "Separator" },
	{ slug: "sheet", title: "Sheet" },
	{ slug: "sidebar", title: "Sidebar" },
	{ slug: "skeleton", title: "Skeleton" },
	{ slug: "slider", title: "Slider" },
	{ slug: "sonner", title: "Sonner" },
	{ slug: "spinner", title: "Spinner" },
	{ slug: "switch", title: "Switch" },
	{ slug: "table", title: "Table" },
	{ slug: "tabs", title: "Tabs" },
	{ slug: "textarea", title: "Textarea" },
	{ slug: "toggle", title: "Toggle" },
	{ slug: "toggle-group", title: "Toggle Group" },
	{ slug: "tooltip", title: "Tooltip" },
];

/** v1 已接线的最小可运行预览（其余节为占位）。 */
export const LIVE_PREVIEW_SLUGS = new Set<string>([
	"accordion",
	"alert",
	"avatar",
	"badge",
	"button",
	"card",
	"checkbox",
	"input",
	"kbd",
	"label",
	"progress",
	"radio-group",
	"separator",
	"skeleton",
	"spinner",
	"switch",
	"tabs",
	"textarea",
	"tooltip",
]);
