import {
  Add01Icon,
  Alert02Icon,
  ArrowDown01Icon,
  ArrowRight01Icon,
  BrowserIcon,
  Cancel01Icon,
  CheckmarkCircle02Icon,
  Delete02Icon,
  Edit02Icon,
  File01Icon,
  FloppyDiskIcon,
  FolderIcon,
  FolderOpenIcon,
  InformationCircleIcon,
  Loading03Icon,
  MultiplicationSignCircleIcon,
  PlayIcon,
  RefreshIcon,
  TerminalIcon,
} from "@hugeicons/core-free-icons";

export const icons = {
  add: Add01Icon,
  alert: Alert02Icon,
  browser: BrowserIcon,
  checkCircle: CheckmarkCircle02Icon,
  chevronDown: ArrowDown01Icon,
  chevronRight: ArrowRight01Icon,
  close: Cancel01Icon,
  delete: Delete02Icon,
  edit: Edit02Icon,
  errorCircle: MultiplicationSignCircleIcon,
  file: File01Icon,
  folder: FolderIcon,
  folderOpen: FolderOpenIcon,
  info: InformationCircleIcon,
  loading: Loading03Icon,
  play: PlayIcon,
  refresh: RefreshIcon,
  save: FloppyDiskIcon,
  terminal: TerminalIcon,
} as const;

export type IconName = keyof typeof icons;
